name: Deploy Hugo site to Pages

on:
  push:
    branches:
      - prod
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-22.04 
    env:
      HUGO_VERSION: 0.121.0
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'      

      - name: Clean npm cache
        run: |  
          npm cache clean --force

      - name: Verify NPX Installation
        run: |
          which npx
          npx --version

      - name: Install dependencies
        run: |
          npm install 
          
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.6.0
        with:
          hugo-version: '0.121.0'
          extended: true

      - name: Build with Hugo
        run: |
          hugo \
            --gc \
            --minify \
            --templateMetrics \
            --templateMetricsHints \
            --forceSyncStatic \
            --baseURL "https://satviksoftech.github.io/"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with: 
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: main
          force_orphan: true      
